version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./heart_neural_network/heart_disease_model.joblib:/app/heart_neural_network/heart_disease_model.joblib
    restart: always
    environment:
      - MODEL_PATH=/app/heart_neural_network/heart_disease_model.joblib 